{% set version = "0.7.5" %}

package:
  name: imread
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/imread/imread-{{ version }}.tar.gz
  sha256: 1a25a9035dbc1ae2e56c15b50904071d555ea197eef58ca1d9117349db470db7

build:
  number: 1
  script:
    - copy /y %LIBRARY_LIB%\libpng.lib %LIBRARY_LIB%\png.lib      # [win]
    - python setup.py build_ext --include-dirs=${PREFIX}/include  # [unix]
    - python setup.py install --single-version-externally-managed --record record.txt
    - del %LIBRARY_LIB%\png.lib  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - msinttypes  # [win]
    - libjpeg-turbo
    - libpng
    - libwebp
    - libtiff
    - zlib         # [win]
  run:
    - python
    - libjpeg-turbo

test:
  imports:
    - imread

about:
  home: https://imread.rtfd.io/
  license: MIT
  license_family: MIT
  license_file: COPYING.MIT
  summary: 'imread: Image reading library'

  description: Mahotas-imread is a simple module to read images into numpy arrays
  doc_url: https://imread.rtfd.io/
  dev_url: https://github.com/luispedro/imread

extra:
  recipe-maintainers:
    - luispedro
