{% set version = "0.7.2" %}

package:
  name: imread
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/imread/imread-{{ version }}.tar.gz
  sha256: c9f1b379b3d5f144fc71982640db0b876929851c3542a11a429e440023a4f15b

build:
  number: 0
  skip: true  # [win and vc<14]
  script:
    - cp %LIBRARY_LIB%\libpng.lib %LIBRARY_LIB%\png.lib  # [win]
    - python setup.py build_ext --include-dirs=${PREFIX}/include  # [unix]
    - python setup.py install --single-version-externally-managed --record record.txt
    - del %LIBRARY_LIB%\png.lib  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - msinttypes  # [win]
    - jpeg
    - libpng
    - libwebp
    - libtiff
    - zlib         # [win]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - jpeg
    - libpng
    - libwebp
    - libtiff
    - zlib         # [win]

test:
  imports:
    - imread

about:
  home: https://imread.rtfd.io/
  license: MIT
  license_family: MIT
  license_file: COPYING.MIT
  summary: 'imread: Image reading library'

  description: Mahotas-imread is a simple module to read images into numpy arrays
  doc_url: https://imread.rtfd.io/
  dev_url: https://github.com/luispedro/imread

extra:
  recipe-maintainers:
    - luispedro
