appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: EJzDyyYWmyAe2e5xBjms0duoSzKODY9stzEzkglyV1UamecsON07lSDP0HWp1JrZL58pmzpd2lUL3vxWP38EVkDp1k4Y1G8AHvF5GIseHfOuxxkI2KigPCa/KqJWtId9hZrMGZH56jjB0FOoquYBdal1ZxIhFoYc+mVwpLOUKtJiCyqu0S9KNRfwduoc+IHn5a70WD4MzxI0LlIw3SPWLGoczfGz8LcMSl5MTEhFc/sGRna8uDcM7dqgLQx60vGTPBOg/axihG9FmhPGxUwZarQiIPE1gXMtoyE2rKkIX1b3XlYycoZ4rlPTlCeUrUp/VoY+eUcDHHWvZ3jdH+X3CdWlo8GiuoXLgo1QDzJiEALePUhcVuXnrOaOZRsogrmtnrG0X3zmMnE8uRF0AibENIDFSib0kt87+HiJCoMbz32p9HPQ3eikof7BE1NAGXfKyKhVg4GOQhm/tpqosF5gTvcafIwiW0V1nSyT0Ab9gMqd6o4FtDdIUokrjFIwTz7mzZCp4ylZuhyspMklAa/LdbcdbncomUVZ04To1mOCA/PhSlICCPBN9JuhxerNC6lt1CVmjWhg01kf1KewbD5gOA7L8rF0HSh9YZPCFAvfIHHzh6gYRCU8Tx2IeqJjoZTMAjbewyag4cMdWHUOcQDh7md76DYUp4YGqX260XWjy98=}
provider:
  win: azure
conda_forge_output_validation: true
